"""Issue #131 — WebSocket dependency pins (deployment contract).

RED-first pins for the prod /ws outage: uvicorn only upgrades WebSocket
requests when a WS library (websockets) is importable in the served venv.
The prod venv built by `uv sync` declared none, so /ws answered a plain
HTTP 404 (sysadmin journal showed uvicorn's "No supported WebSocket
library detected" warning). The fix declares the dependency — uvicorn
auto-detects it; no uvicorn[standard] needed (that extra would pull
uvloop/httptools/watchfiles — out of scope).

Pin groups:
- "dependency pins" must FAIL on base (no websockets declared) and pass
  after the pyproject line + `uv lock`;
- "scope guards" must pass both before and after (bare uvicorn stays, no
  [standard] extras creep in);
- "regression guards" pin the backend route bytes the dependency serves
  (backend/app/api/ws.py is intentionally unchanged).
"""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
PYPROJECT = os.path.join(ROOT, "pyproject.toml")
UV_LOCK = os.path.join(ROOT, "uv.lock")
WS_PY = os.path.join(ROOT, "backend/app/api/ws.py")


def _read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def test_ws_dependency_pins():
    """Issue #131: WebSocket support requires the websockets package — declare it for uv sync."""
    pyproject = _read(PYPROJECT)
    lock = _read(UV_LOCK)
    ws = _read(WS_PY)

    # ---------- dependency pins (RED on base) ----------
    # The exact dependency line, added right after httpx, exactly once.
    assert pyproject.count('    "websockets>=14",') == 1
    assert '    "httpx>=0.27",\n    "websockets>=14",' in pyproject

    # uv.lock really resolves the package (regenerated by `uv lock`, not
    # hand-edited): a `[[package]]` block for websockets — its `name = "..."`
    # line sits at column 0 under `[[package]]`, followed by a concrete
    # `version = "..."` pin (format verified on the httpx block). Anchoring
    # on the leading newline skips the `{ name = "websockets" }` dep refs.
    assert "websockets" in lock
    block_idx = lock.index('\nname = "websockets"\n')
    after_name = lock[block_idx + 1:]  # skip the anchored newline itself
    version_line = after_name.splitlines()[1]
    assert version_line.startswith('version = "'), version_line

    # ---------- scope guards (absence pins) ----------
    # Bare uvicorn stays declared (regression); no [standard] extras creep
    # in (uvicorn[standard]/fastapi[standard] are out of scope for #131).
    assert '    "uvicorn>=0.30",' in pyproject
    assert '"uvicorn[standard]"' not in pyproject
    assert '"fastapi[standard]"' not in pyproject

    # ---------- regression guards (backend contract the dep serves) ----------
    # backend/app/api/ws.py stays byte-identical: the route decorator and
    # the pre-accept token guard (close 4401) are what the dependency lets
    # uvicorn finally reach at the real protocol layer.
    assert '    @app.websocket("/ws")' in ws
    assert "await websocket.close(code=4401)" in ws
